// ═══════════════════════════════════════════════════════════════════════════
// 🔑 syncPhrase — carry a list to another device by typing four words
// ═══════════════════════════════════════════════════════════════════════════
// No accounts, no auth, no login. You read four words off one screen and type
// them into another, and the list follows. The phrase deterministically
// derives a live-room id, so both devices land in the same PartyKit room and
// the existing live-list machinery does the rest.
//
// DELIBERATE TRADEOFF (Pablo's call): the phrase IS the secret, exactly like
// the room id already is elsewhere in this app ("the room id IS the secret —
// no passwords", conversationProtocol.ts).
//
// The banks were 40/40/32/32 = 1,638,400 phrases. Four memorable words SOUND
// like a passphrase, but entropy comes from bank size, and a word out of 40 is
// only ~5.3 bits — so the whole thing was 20.6 bits, which is the same
// strength as FOUR RANDOM CHARACTERS. Measured 2026-09-23: hashing the entire
// old keyspace took 753ms on one CPU core in plain node.
//
// 128 words per bank makes it 268,435,456 (28 bits) — 160x more work to walk.
// Purely additive: isValidSyncPhrase only counts words, so every phrase minted
// under the old banks still resolves to the same room. Nothing to migrate.
//
// It is STILL not a vault, and the ceiling is still the phrase. Anything that
// needs real secrecy must carry its own key and never derive one from these
// words — see docs/DEVICE_SYNC_SPEC.md, where the bundle key is 256 random
// bits in a URL fragment for exactly this reason.

const ADJECTIVES = [
  "neon",
  "funky",
  "silent",
  "sneaky",
  "cosmic",
  "retro",
  "atomic",
  "chunky",
  "dapper",
  "spry",
  "loopy",
  "vibrant",
  "fuzzy",
  "gloomy",
  "slick",
  "brave",
  "wild",
  "gentle",
  "sleepy",
  "peppy",
  "glossy",
  "rowdy",
  "humble",
  "zesty",
  "mellow",
  "crispy",
  "plucky",
  "swanky",
  "jolly",
  "nimble",
  "quiet",
  "sunny",
  "bouncy",
  "velvet",
  "copper",
  "wobbly",
  "breezy",
  "toasty",
  "salty",
  "lucky",
  "amber",
  "balmy",
  "bashful",
  "blissful",
  "bold",
  "brisk",
  "bubbly",
  "buttery",
  "candid",
  "cheeky",
  "chirpy",
  "clever",
  "cloudy",
  "clumsy",
  "cosy",
  "crafty",
  "creamy",
  "crimson",
  "curious",
  "dainty",
  "dazzling",
  "dewy",
  "dizzy",
  "dreamy",
  "dusty",
  "eager",
  "earnest",
  "elastic",
  "fearless",
  "feisty",
  "fizzy",
  "fleecy",
  "floral",
  "foamy",
  "frosty",
  "gallant",
  "giddy",
  "gilded",
  "glassy",
  "gleaming",
  "golden",
  "graceful",
  "grainy",
  "hazy",
  "hearty",
  "honest",
  "hushed",
  "husky",
  "icy",
  "idle",
  "jagged",
  "jaunty",
  "keen",
  "kindly",
  "lanky",
  "leafy",
  "limber",
  "lively",
  "lofty",
  "lunar",
  "marbled",
  "merry",
  "misty",
  "muddy",
  "murky",
  "nifty",
  "noble",
  "opal",
  "patient",
  "pearly",
  "perky",
  "pillowy",
  "polished",
  "prickly",
  "rosy",
  "rugged",
  "rustic",
  "sandy",
  "scarlet",
  "shady",
  "silky",
  "smoky",
  "snappy",
  "solar",
  "sparkly",
  "spicy",
  "spotless",
  "sturdy",
];

const NOUNS = [
  "turtle",
  "lantern",
  "pickle",
  "comet",
  "walrus",
  "muffin",
  "cactus",
  "otter",
  "kettle",
  "puffin",
  "noodle",
  "badger",
  "pebble",
  "raccoon",
  "mango",
  "wombat",
  "satchel",
  "gecko",
  "pancake",
  "ferret",
  "thistle",
  "marble",
  "donkey",
  "waffle",
  "hedgehog",
  "biscuit",
  "lobster",
  "acorn",
  "penguin",
  "teapot",
  "magpie",
  "pumpkin",
  "anchor",
  "sparrow",
  "domino",
  "weasel",
  "kazoo",
  "parsnip",
  "yak",
  "bagel",
  "almond",
  "anvil",
  "apricot",
  "banjo",
  "barnacle",
  "basket",
  "beacon",
  "beetle",
  "bison",
  "blanket",
  "bobbin",
  "bonsai",
  "boulder",
  "bramble",
  "bucket",
  "buffalo",
  "bugle",
  "burrow",
  "button",
  "camel",
  "candle",
  "canoe",
  "carrot",
  "cauldron",
  "chestnut",
  "chimney",
  "cinder",
  "cobweb",
  "compass",
  "cricket",
  "crumpet",
  "cupcake",
  "cymbal",
  "dolphin",
  "dumpling",
  "eagle",
  "feather",
  "fiddle",
  "fossil",
  "fountain",
  "gargoyle",
  "gherkin",
  "ginger",
  "gnome",
  "granite",
  "grotto",
  "harmonica",
  "hazelnut",
  "hornet",
  "iceberg",
  "iguana",
  "jackal",
  "jigsaw",
  "juniper",
  "kayak",
  "kipper",
  "koala",
  "lemon",
  "lettuce",
  "lollipop",
  "lynx",
  "mammoth",
  "mandolin",
  "meadow",
  "meteor",
  "minnow",
  "mitten",
  "monsoon",
  "mushroom",
  "narwhal",
  "nutmeg",
  "obelisk",
  "octopus",
  "olive",
  "orchard",
  "ostrich",
  "pelican",
  "pepper",
  "piano",
  "pigeon",
  "pillow",
  "planet",
  "pretzel",
  "quilt",
  "rhubarb",
  "ribbon",
  "saucer",
  "seagull",
];

const VERBS = [
  "drifts",
  "hums",
  "naps",
  "wanders",
  "juggles",
  "tumbles",
  "skips",
  "hoards",
  "whistles",
  "shuffles",
  "ponders",
  "orbits",
  "gallops",
  "dozes",
  "giggles",
  "sneezes",
  "waltzes",
  "blooms",
  "rattles",
  "paddles",
  "wiggles",
  "salutes",
  "yodels",
  "sulks",
  "bounces",
  "grumbles",
  "twirls",
  "snoozes",
  "hoots",
  "scuttles",
  "flops",
  "sighs",
  "ambles",
  "applauds",
  "balances",
  "barters",
  "basks",
  "beams",
  "bellows",
  "blinks",
  "bobs",
  "bristles",
  "bubbles",
  "bumbles",
  "burrows",
  "canters",
  "capers",
  "chatters",
  "cheers",
  "chimes",
  "chirps",
  "chortles",
  "chuckles",
  "clambers",
  "clatters",
  "coasts",
  "collects",
  "coos",
  "dances",
  "dangles",
  "dashes",
  "dawdles",
  "dips",
  "dives",
  "doodles",
  "drums",
  "echoes",
  "fidgets",
  "fizzes",
  "flaps",
  "flickers",
  "flits",
  "floats",
  "flourishes",
  "flutters",
  "forages",
  "frolics",
  "fumbles",
  "gathers",
  "glides",
  "glimmers",
  "glows",
  "hollers",
  "hovers",
  "jingles",
  "jogs",
  "jostles",
  "lingers",
  "loiters",
  "lopes",
  "lounges",
  "marches",
  "meanders",
  "mumbles",
  "munches",
  "mutters",
  "nibbles",
  "nods",
  "perches",
  "pirouettes",
  "pivots",
  "plods",
  "pounces",
  "prances",
  "preens",
  "prowls",
  "rambles",
  "rehearses",
  "rejoices",
  "rests",
  "rolls",
  "rummages",
  "sashays",
  "saunters",
  "scampers",
  "scrambles",
  "shimmers",
  "shimmies",
  "slumbers",
  "snickers",
  "sparkles",
  "sprints",
  "strolls",
  "strums",
  "struts",
  "swaggers",
  "sways",
  "swoops",
];

const PLACES = [
  "uptown",
  "sideways",
  "downstairs",
  "offshore",
  "backwards",
  "nearby",
  "overboard",
  "homeward",
  "onstage",
  "outback",
  "seaside",
  "midair",
  "underfoot",
  "roadside",
  "skyward",
  "indoors",
  "poolside",
  "upstream",
  "yonder",
  "aloft",
  "ashore",
  "afield",
  "abroad",
  "inland",
  "lakeside",
  "treetop",
  "rooftop",
  "streetwise",
  "campside",
  "harbourside",
  "trackside",
  "hillside",
  "afar",
  "aground",
  "alongside",
  "astern",
  "backstage",
  "bankside",
  "bayside",
  "bedside",
  "below",
  "beneath",
  "beside",
  "beyond",
  "cliffside",
  "clockwise",
  "courtside",
  "creekside",
  "crosstown",
  "curbside",
  "dockside",
  "downhill",
  "downriver",
  "downstream",
  "downtown",
  "eastward",
  "fireside",
  "forward",
  "groundward",
  "headlong",
  "heavenward",
  "homebound",
  "inbound",
  "inboard",
  "inshore",
  "inside",
  "landward",
  "leeward",
  "midstream",
  "midtown",
  "northward",
  "oceanside",
  "offstage",
  "onboard",
  "onshore",
  "outdoors",
  "outward",
  "overhead",
  "overland",
  "overseas",
  "parkside",
  "portside",
  "quayside",
  "ringside",
  "riverside",
  "seaward",
  "shoreward",
  "skyline",
  "southward",
  "stageside",
  "stateside",
  "sternward",
  "streetside",
  "sunward",
  "tableside",
  "townward",
  "trailside",
  "underground",
  "underneath",
  "underwater",
  "upfield",
  "uphill",
  "upland",
  "upriver",
  "uptrack",
  "upward",
  "westward",
  "windward",
  "woodside",
  "bankward",
  "brookside",
  "canyonside",
  "cavernside",
  "cellarside",
  "cornerside",
  "dawnward",
  "duskward",
  "eastside",
  "farmside",
  "fernside",
  "fieldside",
  "gardenside",
  "gateside",
  "glenside",
  "harbourward",
  "hearthside",
  "hedgeside",
  "hilltop",
];

const BANKS = [ADJECTIVES, NOUNS, VERBS, PLACES];

/** How many distinct phrases exist. Surfaced so the tradeoff stays visible. */
export const SYNC_PHRASE_COMBINATIONS = BANKS.reduce(
  (total, bank) => total * bank.length,
  1,
);

export const SYNC_ROOM_PREFIX = "zl_p";

/** A phrase-derived room id: the prefix plus 32 lowercase hex characters. */
export const SYNC_ROOM_PATTERN = /^zl_p[0-9a-f]{32}$/;

function pick(bank) {
  const max = Math.floor(0xffffffff / bank.length) * bank.length;
  const buf = new Uint32Array(1);
  let value;
  // Reject the ragged tail so every word stays equally likely.
  do {
    globalThis.crypto.getRandomValues(buf);
    value = buf[0];
  } while (value >= max);
  return bank[value % bank.length];
}

/** Four words, hyphenated — readable off a screen, typeable on a phone. */
export function generateSyncPhrase() {
  return BANKS.map(pick).join("-");
}

/**
 * Forgiving on input: case, spaces, underscores and stray punctuation all
 * normalize to the same phrase, because people retype these by hand.
 */
export function normalizeSyncPhrase(value) {
  return (value ?? "")
    .toString()
    .toLowerCase()
    .replace(/[^a-z]+/g, " ")
    .trim()
    .split(/\s+/)
    .filter(Boolean)
    .join("-");
}

/** Does this look like a phrase we could derive a room from? */
export function isValidSyncPhrase(value) {
  const words = normalizeSyncPhrase(value).split("-").filter(Boolean);
  return words.length === BANKS.length;
}

/**
 * Deterministic phrase -> room id. Same words on any device, same room.
 * SHA-256 truncated to 128 bits: the hash is a naming function here, not a
 * security boundary — the phrase's own entropy is the ceiling either way.
 */
export async function deriveRoomIdFromPhrase(value) {
  const normalized = normalizeSyncPhrase(value);
  if (!isValidSyncPhrase(normalized)) return "";

  const bytes = new TextEncoder().encode(`ziplist:sync:v1:${normalized}`);
  const digest = await globalThis.crypto.subtle.digest("SHA-256", bytes);
  const hex = Array.from(new Uint8Array(digest))
    .map((b) => b.toString(16).padStart(2, "0"))
    .join("");

  return `${SYNC_ROOM_PREFIX}${hex.slice(0, 32)}`;
}
