/// <reference types="@sveltejs/kit" />
import { build, files, version } from "$service-worker";

const CACHE_NAME = `ziplist-${version}`;

// Assets generated by the build process + static files
const ASSETS = [...build, ...files];
// /version.json is the deploy stamp — the ONE file that must never be served
// from cache. Precaching it would make the app read its own build's stamp
// forever, which defeats the only mechanism that can detect a stale client.
const PRECACHE_ASSETS = ASSETS.filter(
  (path) =>
    !path.endsWith(".wasm") &&
    !path.includes("/ort-") &&
    path !== VERSION_STAMP,
);
const OFFLINE_PAGE = "/offline.html";
const VERSION_STAMP = "/version.json";

function isPrivateRoute(pathname) {
  return (
    pathname.startsWith("/api/") ||
    pathname.startsWith("/import") ||
    pathname.startsWith("/live/")
  );
}

self.addEventListener("install", (event) => {
  event.waitUntil(
    caches.open(CACHE_NAME).then((cache) => cache.addAll(PRECACHE_ASSETS)),
  );
  self.skipWaiting();
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((keys) =>
        Promise.all(
          keys
            .filter((key) => key !== CACHE_NAME)
            .map((key) => caches.delete(key)),
        ),
      ),
  );
  self.clients.claim();
});

self.addEventListener("fetch", (event) => {
  if (event.request.method !== "GET") return;

  const url = new URL(event.request.url);

  // The deploy stamp always goes to the network, uncached, or it cannot do
  // its job of telling a client which build it is actually running.
  if (url.pathname === VERSION_STAMP) return;

  // Keep CDN/model downloads and third-party requests out of the app cache.
  if (url.origin !== self.location.origin) return;

  // Don't cache API calls or private/share routes.
  if (isPrivateRoute(url.pathname)) return;

  // For app assets: cache-first (they're versioned by the build)
  const isAsset = PRECACHE_ASSETS.includes(url.pathname);

  if (isAsset) {
    event.respondWith(
      caches
        .match(event.request)
        .then((cached) => cached || fetch(event.request)),
    );
    return;
  }

  if (event.request.mode === "navigate") {
    event.respondWith(
      fetch(event.request)
        .then((response) => {
          if (response.status === 200) {
            const clone = response.clone();
            caches
              .open(CACHE_NAME)
              .then((cache) => cache.put(event.request, clone));
          }
          return response;
        })
        .catch(async () => {
          const cache = await caches.open(CACHE_NAME);
          return (
            (await cache.match(event.request)) ||
            (await cache.match("/")) ||
            (await cache.match(OFFLINE_PAGE)) ||
            new Response("ZipList is offline.", {
              status: 503,
              headers: { "Content-Type": "text/plain" },
            })
          );
        }),
    );
    return;
  }

  // For other same-origin requests: network-first with cache fallback.
  event.respondWith(
    fetch(event.request)
      .then((response) => {
        // Cache successful responses for offline use
        if (response.status === 200) {
          const clone = response.clone();
          caches
            .open(CACHE_NAME)
            .then((cache) => cache.put(event.request, clone));
        }
        return response;
      })
      .catch(() => caches.match(event.request)),
  );
});
